### ISSUE TITLE
Coverage for to_string()

### ISSUE THREAD

**Issue by NickSimmons97** [stevenarditti/cs4500-a1-pt2#11]
My partner and I are struggling to understand the necessity of your to_string() method. The assignment spec does not state a need to transform the elements of a queue to char*. Lastly, this method is not tested in your test file. Therefore, even if we needed to implement this method, we are unsure of the char* format that you desire. If you do not find this method entirely necessary it would be helpful to remove it. Thank you for your consideration.

**Comment by EvanArmstrong10** [comment]
There was some confusion with the professor-provided utility class. We accepted that change in a PR that contained to_string but we agree that it serves no real purpose, we've removed it.
