### ISSUE TITLE
Change String.h, Object.h, Queue.h to lowercase file names

### ISSUE THREAD

**Issue by danielgaooooo** [stevenarditti/cs4500-a1-pt2#2]
Hey guys, would you mind updating your file names to lowercase (as in, string.h, object.h, queue.h) to match our file spec? Our other implementations from other groups follow this convention this would help our stuff compile. Thanks in advance

**Comment by danielgaooooo** [comment]
it looks like the files on your repo are still uppercase

**Comment by stevenarditti** [comment]
Apologies, I misinterpreted your pull request and thought the change had already been made. File names have been changed and I am closing this issue.
