### ISSUE TITLE
Object and String class

### ISSUE THREAD

**Issue by Xiaocheng-Zhang** [stevenarditti/cs4500-a1-pt2#4]
Can we use the standard object & string classes described on piazza? https://piazza.com/class/k51bluky59n2jr?cid=166

**Comment by Xiaocheng-Zhang** [comment]
Or whatever classes we want if it suitable for all tests.

**Comment by EvanArmstrong10** [comment]
It seems like the agreed upon convention is to have size_t hash() and bool equals() in the string and object classes. I'll make the edit when I get the chance.
