### ISSUE TITLE
Test2

### ISSUE THREAD

**Issue by tx0619s** [stevenarditti/cs4500-a1-pt2#8]
In test2, you have dequeue twice and then done peek. This will result in checking if nullptr is equal to nullptr, which will cause segmentation fault.

We would also like to take more test for examining our implementation.
Thanks

**Comment by Xiaocheng-Zhang** [comment]
For your test t_true(s->equals(s1->trim())); in line 24 test-queue.cpp, if your trim method's output defined as void, this is an invalid syntax. We need call s1->trim() before calling s->equals(Object*)

**Comment by EvanArmstrong10** [comment]
I've fixed the test cases. I am not available right now to make more test cases, but I'll get to those soon. If you have any specific cases you'd like to test against let us know.
