### ISSUE TITLE
test errors

### ISSUE THREAD

**Issue by danielgaooooo** [stevenarditti/cs4500-a1-pt2#9]
https://github.com/stevenarditti/cs4500-a1-pt2/blob/master/test-queue.cpp#L22 should be t_true - there is a double negative here  

https://github.com/stevenarditti/cs4500-a1-pt2/blob/master/test-queue.cpp#L43 should be false, since these 2 strings actually are different - s1 has whitespace, and s has no whitespace, so any string equality test would tell you they are different. same for test on L44.  
  
and to piggy-back on the other issue opened about your tests: b has dequeue called 3 times with only 2 elements, so if this doesn't crash your program, L49's test should actually show b and a still both are the same size.

**Comment by EvanArmstrong10** [comment]
You are right, fixed.
